export const posts = [
  {
    title: "My First AI Agent Update",
    summary: "This is the first content page generated for my AI agent website.",
  },
  {
    title: "Why I Built This Site",
    summary: "I want to build a website that can be updated by AI agents in the future.",
  },
  {
    title: "AI Generated Post",
    summary: "This post was automatically generated by an AI script."
  },
  {
    title: "AI Generated Post",
    summary: "This post was automatically generated by an AI script."
  },
];