const fs = require("fs");
const path = require("path");

const filePath = path.join(__dirname, "../data/posts.ts");

const newPost = {
  title: "AI Generated Post",
  summary: "This post was automatically generated by an AI script."
};

let file = fs.readFileSync(filePath, "utf8");

file = file.replace(
  "];",
  `  {
    title: "${newPost.title}",
    summary: "${newPost.summary}"
  },
];`
);

fs.writeFileSync(filePath, file);

console.log("New post added!");